### ISSUE TITLE
Trim the Gemfile

### ISSUE THREAD

**Issue by boffbowsh** [alphagov/panopticon#271]
When I initially tried to upgrade this to Ruby 2.1, I noticed that the `mechanize` gem installs a [huge amount of dependencies](https://github.com/alphagov/panopticon/blob/31eefc80fc2a6ae77fa8a80314f46946ff69a0df/Gemfile.lock#L201-L209), like something to handle NTLM authentication. We don't use capybara-mechanize to run the test suite, so this should be removed. Along with possibly a bunch of other no-longer-used gems.

**Comment by alext** [comment]
Mechanize is [used in the cucumber tests](https://github.com/alphagov/panopticon/blob/master/features/support/capybara-mechanize.rb). It appears to be necessary because it's testing the journey for a user creating an artefact and being redirected to publisher.

**Comment by boffbowsh** [comment]
Ah ok fair enough.
